# use all encodings
EXP:
  NAME: 'paper__spaceinvaders__iodine__slot_12__sigma_0.40'
MODEL:
  NAME: "IODINE"
  DEVICE: "cuda"
  PARALLEL: False
  DEVICE_IDS: []
DATASET:
  TRAIN: "ATARI"
  VAL: "ATARI"
  TEST: "ATARI"
  DATA_DIR: "/data/public/rw/gautam/static13_dynamic4_mixed/SpaceInvaders-v0"
TRAIN:
  RESUME: True
  # per epoch
  CHECKPOINT_PERIOD: 200
  BATCH_SIZE: 6
  MAX_EPOCHS: 1000
  BASE_LR: 3e-4
  WEIGHT_DECAY: 0.0000
  PRINT_EVERY: 20
  VAL_EVERY: 1000
VAL:
  IS_ON: False
  BATCH_SIZE: 1
ARCH:
  ITERS: 5
  SLOTS: 12
  SIGMA: 0.40

  DIM_LATENT: 64
  IMG_SIZE: 128
  IMG_CHANNELS: 3
  LAYERNORM: True
  STOP_GRADIENT: False
  REF:
    CONV_CHAN: 64
    CONV_LAYERS: 4
    MLP_UNITS: 256
    KERNEL_SIZE: 3
    STRIDE: 2
  DEC:
    CONV_CHAN: 64
    CONV_LAYERS: 4
    KERNEL_SIZE: 3
  ENCODING: [
    # layer normalized graident of posterior
    'posterior',
    'grad_post',
    # input
    'image',
    # predicted mean
    'means',
    # mask
    'mask',
    # mask logits
    'mask_logits',
    # posterior
    'mask_posterior',
    # gradient of means
    'grad_means',
    # gradient of mask
    'grad_mask',
    # likelihood
    'likelihood',
    # leave-one-out likelihood
    'leave_one_out_likelihood',
    # coordinate channel
    'coordinate'
  ]


TENSORBOARD:
  LOG_DIR: "/data/private/tensorboard/"
  IS_ON: True
  TARGETS:
    SCALAR: [
      "loss",
      "kl",
      "likelihood",
      "time_per_iteration",
      "med_time_per_iteration",
      "mse",
      "val_mse"
      ]
    IMAGE: [
      'grid'
      ]

MODEL_DIR: "/data/private/checkpoints"
IMAGE_DIR: "/data/private/images"
